Repository r4ai/remark-callout, pull requests merged in 2024-07, with the labels that each got.

#127 feat: handle data attr values like obsidian
  .changeset/dry-snails-check.md
  packages/remark-callout/src/plugin.test.ts
  packages/remark-callout/src/plugin.ts
Labels: enhancement

#128 feat: add icons in callout
  .changeset/real-penguins-push.md
  bun.lockb
  packages/remark-callout/README.md
  packages/remark-callout/package.json
  packages/remark-callout/src/plugin.test.ts
  packages/remark-callout/src/plugin.ts
  packages/website/src/content/docs/en/index.mdx
Labels: enhancement

#140 chore: replace husky, lint-staged with lefthook
  .husky/pre-commit
  biome.json
  bun.lockb
  lefthook.yml
  lint-staged.config.js
  package.json
  packages/remark-callout/package.json
  packages/website/astro.config.ts
  packages/website/lint-staged.config.js
  packages/website/src/components/CodeBlock.astro
  packages/website/src/components/FeatureCard.tsx
  packages/website/src/components/Header.tsx
  packages/website/src/components/ui/button.tsx
  packages/website/src/components/ui/scroll-area.tsx
  packages/website/src/components/ui/tabs.tsx
  packages/website/src/components/ui/tooltip.tsx
  packages/website/src/content/config.ts
  packages/website/src/layouts/BaseLayout.astro
  packages/website/src/pages/docs/[...slug]/index.astro
  packages/website/src/pages/index.astro
  packages/website/src/pages/playground/_Playground.tsx
  packages/website/src/pages/playground/index.astro
  packages/website/tailwind.config.ts
  remark-callout.code-workspace
Labels: chore

#141 chore: fix `ckeck` and `check:write` command
  biome.json
  bun.lockb
  examples/nextjs/package.json
  lefthook.yml
  package.json
  packages/remark-callout/package.json
  packages/website/biome.json
  packages/website/package.json
  turbo.json
Labels: chore

#142 chore: run `check` script in CI
  .github/workflows/ci.yml
Labels: chore

#143 docs: improve development documentation
  packages/remark-callout/README.md
Labels: documentation

#144 fix: don't render an empty paragraph when the callout body is empty
  .changeset/gentle-drinks-relate.md
  packages/remark-callout/src/plugin.test.ts
  packages/remark-callout/src/plugin.ts
Labels: bug

#146 fix: skip empty callout body
  .changeset/curly-maps-collect.md
  packages/remark-callout/src/plugin.test.ts
  packages/remark-callout/src/plugin.ts
Labels: bug

#149 feat: add `options.titleInner` to specify the HTML element that wraps the text of the callout title
  .changeset/fresh-mirrors-walk.md
  packages/remark-callout/README.md
  packages/remark-callout/src/plugin.test.ts
  packages/remark-callout/src/plugin.ts
Labels: enhancement

#150 fix: don't render content as title in callouts with empty titled paragraph
  .changeset/tidy-rats-hide.md
  packages/remark-callout/src/plugin.test.ts
  packages/remark-callout/src/plugin.ts
Labels: bug

#151 chore: use v8 as coverage reporter
  packages/remark-callout/vitest.config.ts
Labels: chore
